// Generated from modelsinfo.json with customizations
export const defaultProviders = {
  openai: {
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'both',
    apiFormat: 'openai',
    loginUrl: 'https://platform.openai.com/api-keys',
    docsUrl: 'https://platform.openai.com/docs',
    subscriptionUrl: 'https://platform.openai.com/settings/organization/billing/overview',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'gpt-5.5', name: 'GPT-5.5', type: 'text' },
      { id: 'gpt-5.4', name: 'GPT-5.4', type: 'text' },
      { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', type: 'text' },
      { id: 'gpt-5.4-nano', name: 'GPT-5.4 Nano', type: 'text' },
      { id: 'gpt-4.1', name: 'GPT-4.1', type: 'text' },
      { id: 'gpt-4.1-mini', name: 'GPT-4.1 Mini', type: 'text' },
      { id: 'gpt-4.1-nano', name: 'GPT-4.1 Nano', type: 'text' },
      { id: 'gpt-4o', name: 'GPT-4o', type: 'text' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', type: 'text' },
      { id: 'o4-mini', name: 'o4 Mini', type: 'text' },
      { id: 'o3', name: 'o3', type: 'text' },
      { id: 'o3-mini', name: 'o3 Mini', type: 'text' },
      { id: 'o1', name: 'o1', type: 'text' },
      { id: 'o1-mini', name: 'o1 Mini', type: 'text' },
      { id: 'gpt-image-1.5', name: 'GPT Image 1.5', type: 'image' },
      { id: 'gpt-image-1', name: 'GPT Image 1', type: 'image' },
      { id: 'gpt-image-1-mini', name: 'GPT Image 1 Mini', type: 'image' },
      { id: 'dall-e-3', name: 'DALL-E 3', type: 'image' },
      { id: 'sora', name: 'Sora', type: 'video' },
      { id: 'gpt-realtime-1.5', name: 'GPT Realtime 1.5', type: 'audio' },
      { id: 'gpt-realtime-mini', name: 'GPT Realtime Mini', type: 'audio' },
      { id: 'gpt-4o-mini-tts', name: 'GPT-4o Mini TTS', type: 'audio' },
      { id: 'tts-1', name: 'TTS-1', type: 'audio' },
      { id: 'tts-1-hd', name: 'TTS-1 HD', type: 'audio' },
      { id: 'whisper-1', name: 'Whisper-1', type: 'audio' },
      { id: 'gpt-4o-transcribe', name: 'GPT-4o Transcribe', type: 'audio' },
      { id: 'gpt-4o-mini-transcribe', name: 'GPT-4o Mini Transcribe', type: 'audio' },
      { id: 'text-embedding-3-large', name: 'Embedding 3 Large', type: 'embedding' },
      { id: 'text-embedding-3-small', name: 'Embedding 3 Small', type: 'embedding' }
    ]
  },

  github_copilot: {
    name: 'GitHub Copilot',
    baseUrl: 'https://api.githubcopilot.com',
    authType: 'token',
    authHeader: 'Authorization',
    billingType: 'subscription',
    apiFormat: 'openai',
    loginUrl: 'https://github.com/features/copilot',
    docsUrl: 'https://docs.github.com/en/copilot',
    subscriptionUrl: 'https://github.com/settings/copilot',
    accessModes: ['token'],
    oauth: {
      authorizeUrl: 'https://github.com/login/oauth/authorize',
      tokenUrl: 'https://github.com/login/oauth/access_token',
      clientId: 'Iv1.b507a08c87ecfe98',
      scope: 'read:user user:email'
    },
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'gpt-4o', name: 'GPT-4o', type: 'text' },
      { id: 'gpt-4.1', name: 'GPT-4.1', type: 'text' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', type: 'text' },
      { id: 'o4-mini', name: 'o4 Mini', type: 'text' },
      { id: 'o3-mini', name: 'o3 Mini', type: 'text' },
      { id: 'claude-sonnet-4', name: 'Claude Sonnet 4', type: 'text' },
      { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', type: 'text' }
    ]
  },

  openai_codex: {
    name: 'OpenAI Codex (Coding Plan)',
    baseUrl: 'https://api.openai.com/v1',
    authType: 'oauth',
    authHeader: 'Authorization',
    billingType: 'subscription',
    apiFormat: 'openai',
    loginUrl: 'https://platform.openai.com/settings/organization/billing/overview',
    docsUrl: 'https://platform.openai.com/docs',
    subscriptionUrl: 'https://platform.openai.com/settings/organization/billing/overview',
    accessModes: ["oauth"],
    oauth: {
      authorizeUrl: 'https://auth.openai.com/oauth/authorize',
      tokenUrl: 'https://auth.openai.com/oauth/token',
      clientId: 'app_EMoamEEZ73f0CkXaXp7hrann',
      redirectUri: 'http://localhost:1455/auth/callback',
      scope: 'openid profile email offline_access'
    },
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'gpt-5.5', name: 'GPT-5.5', type: 'text' },
      { id: 'gpt-5.4', name: 'GPT-5.4', type: 'text' },
      { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', type: 'text' },
      { id: 'gpt-4.1', name: 'GPT-4.1', type: 'text' },
      { id: 'gpt-4.1-mini', name: 'GPT-4.1 Mini', type: 'text' },
      { id: 'gpt-4o', name: 'GPT-4o', type: 'text' },
      { id: 'o4-mini', name: 'o4 Mini', type: 'text' },
      { id: 'o3', name: 'o3', type: 'text' },
      { id: 'o3-mini', name: 'o3 Mini', type: 'text' }
    ]
  },

  antigravity: {
    name: 'Antigravity (反重力)',
    baseUrl: 'https://api.antigravity.ai/v1',
    authType: 'oauth',
    authHeader: 'Authorization',
    billingType: 'subscription',
    apiFormat: 'openai',
    loginUrl: 'https://antigravity.ai',
    docsUrl: 'https://docs.antigravity.ai',
    subscriptionUrl: 'https://antigravity.ai/billing',
    accessModes: ["oauth"],
    isCommon: true,
    isDomestic: false,
    oauth: {
      authorizeUrl: "http://localhost:5173/api/auth/antigravity/mock-authorize",
      tokenUrl: "http://localhost:5173/api/auth/antigravity/mock-token",
      clientId: "antigravity-client-id-12345",
      redirectUri: "http://localhost:1455/auth/callback",
      scope: "openid profile offline_access"
    },
    models: [
      { id: 'gemini-3.5-flash-medium', name: 'Gemini 3.5 Flash (Medium)', type: 'text' },
      { id: 'gemini-3.5-flash-high', name: 'Gemini 3.5 Flash (High)', type: 'text' },
      { id: 'gemini-3.5-flash-low', name: 'Gemini 3.5 Flash (Low)', type: 'text' },
      { id: 'gemini-3.1-pro-low', name: 'Gemini 3.1 Pro (Low)', type: 'text' },
      { id: 'gemini-3.1-pro-high', name: 'Gemini 3.1 Pro (High)', type: 'text' },
      { id: 'claude-sonnet-4-6-thinking', name: 'Claude Sonnet 4.6 (Thinking)', type: 'text' },
      { id: 'claude-opus-4-6-thinking', name: 'Claude Opus 4.6 (Thinking)', type: 'text' },
      { id: 'gpt-oss-120b-medium', name: 'GPT-OSS 120B (Medium)', type: 'text' },
      { id: 'antigravity-image', name: 'Antigravity Image (图片生成)', type: 'image' },
      { id: 'antigravity-video', name: 'Antigravity Video (视频生成)', type: 'video' }
    ]
  },

  anthropic: {
    name: 'Anthropic (Claude)',
    baseUrl: 'https://api.anthropic.com/v1',
    authType: 'custom-header',
    authHeader: 'x-api-key',
    billingType: 'both',
    apiFormat: 'anthropic',
    loginUrl: 'https://console.anthropic.com/settings/keys',
    docsUrl: 'https://docs.anthropic.com',
    subscriptionUrl: 'https://console.anthropic.com/settings/billing',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'claude-opus-4-6', name: 'Claude Opus 4.6', type: 'text' },
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', type: 'text' },
      { id: 'claude-haiku-4.5', name: 'Claude Haiku 4.5', type: 'text' },
      { id: 'claude-opus-4-20250514', name: 'Claude Opus 4', type: 'text' },
      { id: 'claude-sonnet-4-20250514', name: 'Claude Sonnet 4', type: 'text' },
      { id: 'claude-3-7-sonnet-20250219', name: 'Claude 3.7 Sonnet', type: 'text' },
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet v2', type: 'text' },
      { id: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku', type: 'text' }
    ]
  },

  claude_code: {
    name: 'Claude Code (Subscription)',
    baseUrl: 'https://api.anthropic.com/v1',
    authType: 'oauth',
    authHeader: 'Authorization',
    billingType: 'subscription',
    apiFormat: 'anthropic',
    loginUrl: 'https://claude.ai',
    docsUrl: 'https://docs.anthropic.com',
    subscriptionUrl: 'https://claude.ai/settings/billing',
    accessModes: ["oauth"],
    oauth: {
      authorizeUrl: 'https://claude.ai/oauth/authorize',
      tokenUrl: 'https://api.anthropic.com/v1/oauth/token',
      clientId: '9d1c250a-e61b-44d9-88ed-5944d1962f5e',
      redirectUri: 'http://localhost:54545/callback',
      scope: 'user:profile user:inference'
    },
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'claude-opus-4-6', name: 'Claude Opus 4.6', type: 'text' },
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', type: 'text' },
      { id: 'claude-haiku-4-5', name: 'Claude Haiku 4.5', type: 'text' },
      { id: 'claude-opus-4-20250514', name: 'Claude Opus 4', type: 'text' },
      { id: 'claude-sonnet-4-20250514', name: 'Claude Sonnet 4', type: 'text' },
      { id: 'claude-3-7-sonnet-20250219', name: 'Claude 3.7 Sonnet', type: 'text' },
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet v2', type: 'text' }
    ]
  },

  cursor: {
    name: 'Cursor',
    baseUrl: 'https://api2.cursor.sh/v1',
    authType: 'oauth',
    authHeader: 'Authorization',
    billingType: 'subscription',
    apiFormat: 'openai',
    loginUrl: 'https://cursor.com',
    docsUrl: 'https://docs.cursor.com',
    subscriptionUrl: 'https://cursor.com/settings',
    accessModes: ["oauth"],
    oauth: {
      authorizeUrl: 'https://cursor.com/loginDeepControl',
      tokenUrl: 'https://api2.cursor.sh/auth/poll',
      scope: '(PKCE device flow)'
    },
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'claude-opus-4-6', name: 'Claude Opus 4.6', type: 'text' },
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', type: 'text' },
      { id: 'claude-sonnet-4', name: 'Claude Sonnet 4', type: 'text' },
      { id: 'gpt-5.4', name: 'GPT-5.4', type: 'text' },
      { id: 'gpt-4.1', name: 'GPT-4.1', type: 'text' },
      { id: 'gpt-4o', name: 'GPT-4o', type: 'text' },
      { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', type: 'text' },
      { id: 'cursor-small', name: 'Cursor Small', type: 'text' }
    ]
  },

  google: {
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    authType: 'query-key',
    authHeader: 'Authorization',
    billingType: 'both',
    apiFormat: 'google',
    loginUrl: 'https://aistudio.google.com/app/apikey',
    docsUrl: 'https://ai.google.dev/docs',
    subscriptionUrl: 'https://aistudio.google.com/app/plan',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro Preview', type: 'text' },
      { id: 'gemini-3-flash-preview', name: 'Gemini 3 Flash Preview', type: 'text' },
      { id: 'gemini-3.1-flash-lite-preview', name: 'Gemini 3.1 Flash-Lite Preview', type: 'text' },
      { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', type: 'text' },
      { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', type: 'text' },
      { id: 'gemini-2.5-flash-lite', name: 'Gemini 2.5 Flash-Lite', type: 'text' },
      { id: 'imagen-4', name: 'Imagen 4', type: 'image' },
      { id: 'veo-3.1-generate-preview', name: 'Veo 3.1 Preview', type: 'video' },
      { id: 'veo-3.1-lite-generate-preview', name: 'Veo 3.1 Lite Preview', type: 'video' },
      { id: 'gemini-2.5-flash-preview-tts', name: 'Gemini 2.5 Flash TTS', type: 'audio' },
      { id: 'gemini-2.5-pro-preview-tts', name: 'Gemini 2.5 Pro TTS', type: 'audio' },
      { id: 'gemini-embedding-2-preview', name: 'Gemini Embedding 2', type: 'embedding' },
      { id: 'text-embedding-004', name: 'Text Embedding 004', type: 'embedding' }
    ]
  },

  custom: {
    name: 'Custom',
    baseUrl: 'http://api1.1share.ai:8317/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: '',
    docsUrl: '',
    subscriptionUrl: '',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: true,
    models: [
      { id: 'deepseek-v4-flash', name: 'DeepSeek v4 Flash', type: 'text' },
      { id: 'deepseek-v4-pro', name: 'DeepSeek v4 Pro', type: 'text' },
      { id: 'MiniMax-M2.7', name: 'MiniMax M2.7', type: 'text' },
      { id: 'MiniMax-M2.5', name: 'MiniMax M2.5', type: 'text' },
      { id: 'MiniMax-M2.7-Highspeed', name: 'MiniMax M2.7 Highspeed', type: 'text' },
      { id: 'MiniMax-M2.5-Highspeed', name: 'MiniMax M2.5 Highspeed', type: 'text' },
      { id: 'kimi-k2.5', name: 'Kimi K2.5', type: 'text' },
      { id: 'kimi-k2.6', name: 'Kimi K2.6', type: 'text' },
      { id: 'gpt-5.4', name: 'GPT-5.4', type: 'text' },
      { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', type: 'text' },
      { id: 'gpt-5.3-codex-spark', name: 'GPT-5.3 Codex Spark', type: 'text' },
      { id: 'gpt-5.5', name: 'GPT-5.5', type: 'text' },
      { id: 'gemini-3-flash', name: 'Gemini 3 Flash', type: 'text' },
      { id: 'gemini-3-pro-low', name: 'Gemini 3 Pro Low', type: 'text' },
      { id: 'gemini-3.1-pro-low', name: 'Gemini 3.1 Pro Low', type: 'text' },
      { id: 'gemini-3.1-flash-lite', name: 'Gemini 3.1 Flash Lite', type: 'text' },
      { id: 'Gemini 3.5 Flash', name: 'Gemini 3.5 Flash', type: 'text' },
      { id: 'gemini-3.5-flash-low', name: 'Gemini 3.5 Flash Low', type: 'text' },
      { id: 'claude-opus-4-6-thinking', name: 'Claude Opus 4.6 (Thinking)', type: 'text' },
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6', type: 'text' },
      { id: 'glm-5', name: 'GLM 5', type: 'text' },
      { id: 'glm-5.1', name: 'GLM 5.1', type: 'text' },
      { id: 'qwen3.7-max', name: 'Qwen3.7 Max', type: 'text' },
      { id: 'gpt-image-2', name: 'GPT Image 2', type: 'image' },
      { id: 'gpt-oss-120b-medium', name: 'GPT OSS 120B Medium', type: 'text' },
      { id: 'mimo-v2.5-pro', name: 'Mimo v2.5 Pro', type: 'text' }
    ]
  },

  deepseek: {
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.deepseek.com/api_keys',
    docsUrl: 'https://platform.deepseek.com/api-docs',
    subscriptionUrl: 'https://platform.deepseek.com/top_up',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: true,
    models: [
      { id: 'deepseek-chat', name: 'DeepSeek-V3', type: 'text' },
      { id: 'deepseek-reasoner', name: 'DeepSeek-R1', type: 'text' },
      { id: 'deepseek-v4-flash', name: 'DeepSeek v4 Flash', type: 'text' },
      { id: 'deepseek-v4-pro', name: 'DeepSeek v4 Pro', type: 'text' }
    ]
  },

  moonshot: {
    name: '月之暗面 (Kimi/Moonshot)',
    baseUrl: 'https://api.moonshot.cn/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.moonshot.cn/console/api-keys',
    docsUrl: 'https://platform.moonshot.cn/docs',
    subscriptionUrl: 'https://platform.moonshot.cn/console/account',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: true,
    models: [
      { id: 'moonshot-v1-8k', name: 'Moonshot V1 8K', type: 'text' },
      { id: 'moonshot-v1-32k', name: 'Moonshot V1 32K', type: 'text' },
      { id: 'moonshot-v1-128k', name: 'Moonshot V1 128K', type: 'text' },
      { id: 'moonshot-v1-8k-vision-preview', name: 'Moonshot V1 8K Vision', type: 'text' },
      { id: 'moonshot-v1-32k-vision-preview', name: 'Moonshot V1 32K Vision', type: 'text' },
      { id: 'moonshot-v1-128k-vision-preview', name: 'Moonshot V1 128K Vision', type: 'text' },
      { id: 'kimi-k2.5', name: 'Kimi K2.5', type: 'text' },
      { id: 'kimi-k2.6', name: 'Kimi K2.6', type: 'text' },
      { id: 'moonshot-v1-auto', name: 'Moonshot V1 Auto', type: 'text' }
    ]
  },

  qwen: {
    name: '百炼',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://dashscope.console.aliyun.com/apiKey',
    docsUrl: 'https://help.aliyun.com/zh/dashscope/',
    subscriptionUrl: 'https://dashscope.console.aliyun.com/billing',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: true,
    models: [
      { id: 'qwen-max', name: 'Qwen Max', type: 'text' },
      { id: 'qwen-plus', name: 'Qwen Plus', type: 'text' },
      { id: 'qwen-turbo', name: 'Qwen Turbo', type: 'text' },
      { id: 'qwen-long', name: 'Qwen Long (长文本)', type: 'text' },
      { id: 'qwen3.7-max', name: 'Qwen3.7 Max', type: 'text' },
      { id: 'qwen3.7-plus', name: 'Qwen3.7 Plus', type: 'text' },
      { id: 'qwen3.6-plus', name: 'Qwen3.6 Plus', type: 'text' },
      { id: 'qwen3.6-flash', name: 'Qwen3.6 Flash', type: 'text' },
      { id: 'qwen3.5-plus', name: 'Qwen3.5 Plus', type: 'text' },
      { id: 'qwen3.5-flash', name: 'Qwen3.5 Flash', type: 'text' },
      { id: 'qwen3-max', name: 'Qwen3 Max', type: 'text' },
      { id: 'qwen3-vl-plus', name: 'Qwen3 VL Plus', type: 'text' },
      { id: 'qwen3-coder-plus', name: 'Qwen3 Coder Plus', type: 'text' },
      { id: 'qwq-plus', name: 'QwQ Plus (推理)', type: 'text' },
      { id: 'qvq-max', name: 'QVQ Max (视觉推理)', type: 'text' },
      { id: 'deepseek-v3', name: 'DeepSeek-V3', type: 'text' },
      { id: 'deepseek-r1', name: 'DeepSeek-R1 (推理)', type: 'text' },
      { id: 'qwen-coder-plus', name: 'Qwen Coder Plus', type: 'text' },
      { id: 'qwen-coder-turbo', name: 'Qwen Coder Turbo', type: 'text' },
      { id: 'qwen-math-plus', name: 'Qwen Math Plus', type: 'text' },
      { id: 'qwen-math-turbo', name: 'Qwen Math Turbo', type: 'text' },
      { id: 'qwen-vl-max', name: 'Qwen VL Max (视觉)', type: 'text' },
      { id: 'qwen-vl-plus', name: 'Qwen VL Plus (视觉)', type: 'text' },
      { id: 'qwen-omni-turbo', name: 'Qwen Omni Turbo', type: 'text' }
    ]
  },

  zhipu: {
    name: '智谱AI (Zhipu/GLM)',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    docsUrl: 'https://open.bigmodel.cn/dev/api',
    subscriptionUrl: 'https://open.bigmodel.cn/pricing',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: true,
    models: [
      { id: 'glm-4-plus', name: 'GLM-4 Plus', type: 'text' },
      { id: 'glm-4-0520', name: 'GLM-4 (0520)', type: 'text' },
      { id: 'glm-4-air', name: 'GLM-4 Air', type: 'text' },
      { id: 'glm-4-airx', name: 'GLM-4 AirX', type: 'text' },
      { id: 'glm-4-long', name: 'GLM-4 Long', type: 'text' },
      { id: 'glm-4-flashx', name: 'GLM-4 FlashX', type: 'text' },
      { id: 'glm-4-flash', name: 'GLM-4 Flash', type: 'text' },
      { id: 'glm-4v-plus', name: 'GLM-4V Plus (视觉)', type: 'text' },
      { id: 'glm-4v', name: 'GLM-4V (视觉)', type: 'text' },
      { id: 'glm-4v-flash', name: 'GLM-4V Flash (视觉)', type: 'text' },
      { id: 'cogview-3-plus', name: 'CogView-3 Plus', type: 'image' },
      { id: 'cogview-3', name: 'CogView-3', type: 'image' },
      { id: 'cogvideox', name: 'CogVideoX', type: 'video' },
      { id: 'cogvideox-flash', name: 'CogVideoX Flash', type: 'video' },
      { id: 'embedding-3', name: 'Embedding-3', type: 'embedding' },
      { id: 'embedding-2', name: 'Embedding-2', type: 'embedding' }
    ]
  },

  baidu: {
    name: '百度文心 (ERNIE)',
    baseUrl: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat',
    authType: 'query-token',
    authHeader: 'Authorization',
    billingType: 'both',
    apiFormat: 'baidu',
    loginUrl: 'https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application',
    docsUrl: 'https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html',
    subscriptionUrl: 'https://console.bce.baidu.com/billing/#/account/index',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'ernie-4.5-8k-preview', name: 'ERNIE 4.5 8K', type: 'text' },
      { id: 'ernie-4.5-turbo-8k-preview', name: 'ERNIE 4.5 Turbo 8K', type: 'text' },
      { id: 'ernie-4.5-turbo-128k-preview', name: 'ERNIE 4.5 Turbo 128K', type: 'text' },
      { id: 'completions_pro', name: 'ERNIE 4.0', type: 'text' },
      { id: 'ernie-4.0-turbo-8k', name: 'ERNIE 4.0 Turbo 8K', type: 'text' },
      { id: 'ernie-4.0-turbo-128k', name: 'ERNIE 4.0 Turbo 128K', type: 'text' },
      { id: 'completions', name: 'ERNIE 3.5 8K', type: 'text' },
      { id: 'ernie-3.5-128k', name: 'ERNIE 3.5 128K', type: 'text' },
      { id: 'ernie-speed-128k', name: 'ERNIE Speed 128K', type: 'text' },
      { id: 'ernie-speed-pro-128k', name: 'ERNIE Speed Pro 128K', type: 'text' },
      { id: 'ernie-lite-128k', name: 'ERNIE Lite 128K', type: 'text' },
      { id: 'ernie-lite-pro-128k', name: 'ERNIE Lite Pro 128K', type: 'text' },
      { id: 'ernie-tiny-8k', name: 'ERNIE Tiny 8K', type: 'text' }
    ]
  },

  doubao: {
    name: '豆包 (ByteDance/火山方舟)',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    docsUrl: 'https://www.volcengine.com/docs/82379',
    subscriptionUrl: 'https://console.volcengine.com/finance/unifiedBilling/detail',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: true,
    models: [
      { id: 'doubao-seed-2-0-pro-260215', name: 'Doubao Seed 2.0 Pro 260215', type: 'text' },
      { id: 'doubao-1.5-pro-32k', name: 'Doubao 1.5 Pro 32K', type: 'text' },
      { id: 'doubao-1.5-pro-256k', name: 'Doubao 1.5 Pro 256K', type: 'text' },
      { id: 'doubao-1.5-lite-32k', name: 'Doubao 1.5 Lite 32K', type: 'text' },
      { id: 'doubao-1.5-vision-pro-32k', name: 'Doubao 1.5 Vision Pro', type: 'text' },
      { id: 'doubao-pro-32k', name: 'Doubao Pro 32K', type: 'text' },
      { id: 'doubao-pro-128k', name: 'Doubao Pro 128K', type: 'text' },
      { id: 'doubao-pro-256k', name: 'Doubao Pro 256K', type: 'text' },
      { id: 'doubao-lite-32k', name: 'Doubao Lite 32K', type: 'text' },
      { id: 'doubao-lite-128k', name: 'Doubao Lite 128K', type: 'text' },
      { id: 'seedream', name: 'Seedream 图片生成', type: 'image' },
      { id: 'doubao-embedding-large', name: 'Doubao Embedding Large', type: 'embedding' }
    ]
  },

  minimax: {
    name: 'MiniMax (海螺AI)',
    baseUrl: 'https://api.minimax.chat/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    docsUrl: 'https://platform.minimaxi.com/document/Announcement',
    subscriptionUrl: 'https://platform.minimaxi.com/user-center/basic-information',
    accessModes: ["apikey"],
    oauth: {
      authorizeUrl: 'https://platform.minimaxi.com/oauth/authorize',
      tokenUrl: 'https://platform.minimaxi.com/oauth/token',
      scope: 'api'
    },
    isCommon: true,
    isDomestic: true,
    models: [
      { id: 'MiniMax-M2.7', name: 'MiniMax M2.7', type: 'text' },
      { id: 'MiniMax-M2.7-highspeed', name: 'MiniMax M2.7 Highspeed', type: 'text' },
      { id: 'MiniMax-M2.5', name: 'MiniMax M2.5', type: 'text' },
      { id: 'MiniMax-M2.5-highspeed', name: 'MiniMax M2.5 Highspeed', type: 'text' },
      { id: 'MiniMax-M2.1', name: 'MiniMax M2.1', type: 'text' },
      { id: 'MiniMax-M2.1-highspeed', name: 'MiniMax M2.1 Highspeed', type: 'text' },
      { id: 'MiniMax-M2', name: 'MiniMax M2', type: 'text' },
      { id: 'speech-2.8-hd', name: 'Speech 2.8 HD', type: 'audio' },
      { id: 'speech-2.8-turbo', name: 'Speech 2.8 Turbo', type: 'audio' },
      { id: 'speech-2.6-hd', name: 'Speech 2.6 HD', type: 'audio' },
      { id: 'speech-2.6-turbo', name: 'Speech 2.6 Turbo', type: 'audio' },
      { id: 'speech-02-hd', name: 'Speech 02 HD', type: 'audio' },
      { id: 'speech-02-turbo', name: 'Speech 02 Turbo', type: 'audio' },
      { id: 'music-2.0', name: 'Music 2.0', type: 'audio' },
      { id: 'minimax-hailuo-2.3', name: 'MiniMax Hailuo 2.3', type: 'video' },
      { id: 'minimax-hailuo-2.3-fast', name: 'MiniMax Hailuo 2.3 Fast', type: 'video' },
      { id: 'minimax-hailuo-02', name: 'MiniMax Hailuo 02', type: 'video' },
      { id: 'image-01', name: 'Image 01', type: 'image' },
      { id: 'image-01-live', name: 'Image 01 Live', type: 'image' }
    ]
  },

  siliconflow: {
    name: 'SiliconFlow (硅基流动)',
    baseUrl: 'https://api.siliconflow.cn/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://cloud.siliconflow.cn/account/ak',
    docsUrl: 'https://docs.siliconflow.cn',
    subscriptionUrl: 'https://cloud.siliconflow.cn/account/charge',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3', type: 'text' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1', type: 'text' },
      { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen2.5 72B', type: 'text' },
      { id: 'Qwen/Qwen2.5-32B-Instruct', name: 'Qwen2.5 32B', type: 'text' },
      { id: 'Qwen/Qwen2.5-7B-Instruct', name: 'Qwen2.5 7B', type: 'text' },
      { id: 'Qwen/Qwen2.5-Coder-32B-Instruct', name: 'Qwen2.5 Coder 32B', type: 'text' },
      { id: 'Qwen/QwQ-32B', name: 'QwQ 32B', type: 'text' },
      { id: 'Pro/Qwen/Qwen2.5-VL-7B-Instruct', name: 'Qwen2.5 VL 7B', type: 'text' },
      { id: 'THUDM/glm-4-9b-chat', name: 'GLM-4 9B', type: 'text' },
      { id: 'meta-llama/Llama-3.3-70B-Instruct', name: 'Llama 3.3 70B', type: 'text' },
      { id: 'google/gemma-2-27b-it', name: 'Gemma 2 27B', type: 'text' },
      { id: 'stabilityai/stable-diffusion-3-5-large', name: 'SD 3.5 Large', type: 'image' },
      { id: 'black-forest-labs/FLUX.1-schnell', name: 'FLUX.1 Schnell', type: 'image' },
      { id: 'black-forest-labs/FLUX.1-dev', name: 'FLUX.1 Dev', type: 'image' }
    ]
  },

  stepfun: {
    name: '阶跃星辰 (StepFun)',
    baseUrl: 'https://api.stepfun.com/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.stepfun.com/interface-key',
    docsUrl: 'https://platform.stepfun.com/docs/overview/concept',
    subscriptionUrl: 'https://platform.stepfun.com/account-management',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'step-2-16k', name: 'Step-2 16K', type: 'text' },
      { id: 'step-2-16k-exp', name: 'Step-2 16K Exp', type: 'text' },
      { id: 'step-1-200k', name: 'Step-1 200K', type: 'text' },
      { id: 'step-1-128k', name: 'Step-1 128K', type: 'text' },
      { id: 'step-1-32k', name: 'Step-1 32K', type: 'text' },
      { id: 'step-1v-32k', name: 'Step-1V 32K (视觉)', type: 'text' },
      { id: 'step-1.5v-mini', name: 'Step-1.5V Mini (视觉)', type: 'text' },
      { id: 'step-1x-medium', name: 'Step-1X Medium (图片)', type: 'image' }
    ]
  },

  mistral: {
    name: 'Mistral AI',
    baseUrl: 'https://api.mistral.ai/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.mistral.ai/api-keys',
    docsUrl: 'https://docs.mistral.ai',
    subscriptionUrl: 'https://console.mistral.ai/billing',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: false,
    models: [
      { id: 'mistral-large-latest', name: 'Mistral Large', type: 'text' },
      { id: 'mistral-medium-latest', name: 'Mistral Medium', type: 'text' },
      { id: 'mistral-small-latest', name: 'Mistral Small', type: 'text' },
      { id: 'open-mistral-nemo', name: 'Mistral Nemo', type: 'text' },
      { id: 'codestral-latest', name: 'Codestral', type: 'text' },
      { id: 'pixtral-large-latest', name: 'Pixtral Large (视觉)', type: 'text' },
      { id: 'pixtral-12b-2409', name: 'Pixtral 12B (视觉)', type: 'text' },
      { id: 'mistral-embed', name: 'Mistral Embed', type: 'embedding' }
    ]
  },

  xai: {
    name: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://accounts.x.ai',
    docsUrl: 'https://docs.x.ai',
    subscriptionUrl: 'https://accounts.x.ai',
    accessModes: ["apikey"],
    isCommon: true,
    isDomestic: false,
    models: [
      { id: 'grok-3', name: 'Grok 3', type: 'text' },
      { id: 'grok-3-mini', name: 'Grok 3 Mini', type: 'text' },
      { id: 'grok-3-fast', name: 'Grok 3 Fast', type: 'text' },
      { id: 'grok-3-mini-fast', name: 'Grok 3 Mini Fast', type: 'text' },
      { id: 'grok-2-vision-1212', name: 'Grok 2 Vision', type: 'text' },
      { id: 'grok-2-1212', name: 'Grok 2', type: 'text' },
      { id: 'grok-vision-beta', name: 'Grok Vision Beta', type: 'text' }
    ]
  },

  cohere: {
    name: 'Cohere',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://dashboard.cohere.com/api-keys',
    docsUrl: 'https://docs.cohere.com/docs/compatibility-api',
    subscriptionUrl: 'https://dashboard.cohere.com',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'command-a-03-2025', name: 'Command A', type: 'text' },
      { id: 'command-r-plus-08-2024', name: 'Command R+', type: 'text' },
      { id: 'command-r-08-2024', name: 'Command R', type: 'text' },
      { id: 'command-r7b-12-2024', name: 'Command R7B', type: 'text' },
      { id: 'embed-v4.0', name: 'Embed v4.0', type: 'embedding' },
      { id: 'embed-multilingual-v3.0', name: 'Embed Multilingual v3.0', type: 'embedding' },
      { id: 'rerank-v3.5', name: 'Rerank v3.5', type: 'text' }
    ]
  },

  groq: {
    name: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs/openai',
    subscriptionUrl: 'https://console.groq.com',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: false,
    models: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile', type: 'text' },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant', type: 'text' },
      { id: 'llama-3.2-90b-vision-preview', name: 'Llama 3.2 90B Vision', type: 'text' },
      { id: 'llama-3.2-11b-vision-preview', name: 'Llama 3.2 11B Vision', type: 'text' },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B', type: 'text' },
      { id: 'gemma2-9b-it', name: 'Gemma 2 9B', type: 'text' },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill 70B', type: 'text' },
      { id: 'qwen-qwq-32b', name: 'QwQ 32B', type: 'text' }
    ]
  },

  perplexity: {
    name: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://www.perplexity.ai/settings/api',
    docsUrl: 'https://docs.perplexity.ai',
    subscriptionUrl: 'https://www.perplexity.ai/settings/api',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: false,
    models: [
      { id: 'sonar', name: 'Sonar', type: 'text' },
      { id: 'sonar-pro', name: 'Sonar Pro', type: 'text' },
      { id: 'sonar-reasoning', name: 'Sonar Reasoning', type: 'text' },
      { id: 'sonar-reasoning-pro', name: 'Sonar Reasoning Pro', type: 'text' },
      { id: 'sonar-deep-research', name: 'Sonar Deep Research', type: 'text' }
    ]
  },

  openrouter: {
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://openrouter.ai/settings/keys',
    docsUrl: 'https://openrouter.ai/docs/quickstart',
    subscriptionUrl: 'https://openrouter.ai/settings/credits',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'openai/gpt-4o', name: 'OpenAI GPT-4o', type: 'text' },
      { id: 'openai/gpt-4.1', name: 'OpenAI GPT-4.1', type: 'text' },
      { id: 'openai/o3', name: 'OpenAI o3', type: 'text' },
      { id: 'anthropic/claude-sonnet-4', name: 'Claude Sonnet 4', type: 'text' },
      { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet', type: 'text' },
      { id: 'google/gemini-2.5-pro-preview', name: 'Gemini 2.5 Pro', type: 'text' },
      { id: 'google/gemini-2.5-flash-preview', name: 'Gemini 2.5 Flash', type: 'text' },
      { id: 'deepseek/deepseek-chat', name: 'DeepSeek V3', type: 'text' },
      { id: 'deepseek/deepseek-r1', name: 'DeepSeek R1', type: 'text' },
      { id: 'x-ai/grok-3', name: 'Grok 3', type: 'text' },
      { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B', type: 'text' },
      { id: 'qwen/qwen-2.5-72b-instruct', name: 'Qwen2.5 72B', type: 'text' },
      { id: 'mistralai/mistral-large-latest', name: 'Mistral Large', type: 'text' }
    ]
  },

  together: {
    name: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://api.together.ai/settings/api-keys',
    docsUrl: 'https://docs.together.ai/docs/openai-api-compatibility',
    subscriptionUrl: 'https://api.together.ai/settings/billing',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', name: 'Llama 4 Maverick', type: 'text' },
      { id: 'meta-llama/Llama-4-Scout-17B-16E-Instruct', name: 'Llama 4 Scout', type: 'text' },
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', name: 'Llama 3.3 70B Turbo', type: 'text' },
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3', type: 'text' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1', type: 'text' },
      { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', name: 'Qwen2.5 72B Turbo', type: 'text' },
      { id: 'Qwen/QwQ-32B', name: 'QwQ 32B', type: 'text' },
      { id: 'mistralai/Mixtral-8x22B-Instruct-v0.1', name: 'Mixtral 8x22B', type: 'text' },
      { id: 'black-forest-labs/FLUX.1-schnell-Free', name: 'FLUX.1 Schnell', type: 'image' },
      { id: 'black-forest-labs/FLUX.1.1-pro', name: 'FLUX 1.1 Pro', type: 'image' }
    ]
  },

  fireworks: {
    name: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://app.fireworks.ai/api-keys',
    docsUrl: 'https://docs.fireworks.ai/tools-sdks/openai-compatibility',
    subscriptionUrl: 'https://app.fireworks.ai',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', name: 'Llama 3.3 70B', type: 'text' },
      { id: 'accounts/fireworks/models/llama-v3p1-405b-instruct', name: 'Llama 3.1 405B', type: 'text' },
      { id: 'accounts/fireworks/models/deepseek-v3', name: 'DeepSeek V3', type: 'text' },
      { id: 'accounts/fireworks/models/deepseek-r1', name: 'DeepSeek R1', type: 'text' },
      { id: 'accounts/fireworks/models/qwen2p5-72b-instruct', name: 'Qwen2.5 72B', type: 'text' },
      { id: 'accounts/fireworks/models/mixtral-8x22b-instruct', name: 'Mixtral 8x22B', type: 'text' },
      { id: 'accounts/fireworks/models/firefunction-v2', name: 'FireFunction V2', type: 'text' }
    ]
  },

  tencent_hunyuan: {
    name: '腾讯混元 (HunYuan)',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.cloud.tencent.com/hunyuan/api-key',
    docsUrl: 'https://cloud.tencent.com/document/product/1729/111007',
    subscriptionUrl: 'https://console.cloud.tencent.com/expense',
    accessModes: ["apikey"],
    isCommon: false,
    isDomestic: true,
    models: [
      { id: 'hunyuan-turbos-latest', name: 'HunYuan TurboS Latest', type: 'text' },
      { id: 'hunyuan-t1-latest', name: 'HunYuan T1 Latest', type: 'text' },
      { id: 'hunyuan-large', name: 'HunYuan Large', type: 'text' },
      { id: 'hunyuan-turbo', name: 'HunYuan Turbo', type: 'text' },
      { id: 'hunyuan-standard-256k', name: 'HunYuan Standard 256K', type: 'text' },
      { id: 'hunyuan-lite', name: 'HunYuan Lite', type: 'text' },
      { id: 'hunyuan-vision', name: 'HunYuan Vision', type: 'text' },
      { id: 'hunyuan-code', name: 'HunYuan Code', type: 'text' }
    ]
  },

};
