module.exports = {
  moonshot: {
    name: 'Moonshot AI (Kimi)',
    baseUrl: 'https://api.moonshot.cn/v1',
                                   
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.moonshot.cn/console/api-keys',
    docsUrl: 'https://platform.moonshot.cn/docs',
    subscriptionUrl: 'https://platform.moonshot.cn/console/account',
    accessModes: ['apikey'],
    models: [

      { id: 'kimi-k2.5', name: 'Kimi K2.5', type: 'text' },
      { id: 'kimi-k2-0905-preview', name: 'Kimi K2 0905 Preview', type: 'text' },
      { id: 'kimi-k2-0711-preview', name: 'Kimi K2 0711 Preview', type: 'text' },
      { id: 'kimi-k2-turbo-preview', name: 'Kimi K2 Turbo Preview', type: 'text' },
      { id: 'kimi-k2-thinking', name: 'Kimi K2 Thinking (深入推理)', type: 'text' },
      { id: 'kimi-k2-thinking-turbo', name: 'Kimi K2 Thinking Turbo', type: 'text' },
      { id: 'moonshot-v1-8k', name: 'Moonshot V1 8K', type: 'text' },
      { id: 'moonshot-v1-32k', name: 'Moonshot V1 32K', type: 'text' },
      { id: 'moonshot-v1-128k', name: 'Moonshot V1 128K', type: 'text' },
      { id: 'moonshot-v1-8k-vision-preview', name: 'Moonshot V1 8K Vision', type: 'text' },
      { id: 'moonshot-v1-32k-vision-preview', name: 'Moonshot V1 32K Vision', type: 'text' },
      { id: 'moonshot-v1-128k-vision-preview', name: 'Moonshot V1 128K Vision', type: 'text' }
    ],
  },

  qwen: {
    name: '通义千问 (Qwen)',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://dashscope.console.aliyun.com/apiKey',
    docsUrl: 'https://help.aliyun.com/zh/dashscope/',
    subscriptionUrl: 'https://dashscope.console.aliyun.com/billing',
    accessModes: ['apikey'],
    models: [
      // Qwen3 flagship (API names)
      { id: 'qwen3-max', name: 'Qwen3 Max', type: 'text' },
      { id: 'qwen-plus', name: 'Qwen Plus (Qwen3.6)', type: 'text' },
      { id: 'qwen-turbo', name: 'Qwen Turbo', type: 'text' },
      { id: 'qwen-long', name: 'Qwen Long', type: 'text' },
      { id: 'qwen-max', name: 'Qwen Max', type: 'text' },
      // Qwen3 open-weight
      { id: 'qwen3-235b-a22b', name: 'Qwen3 235B-A22B', type: 'text' },
      { id: 'qwen3-32b', name: 'Qwen3 32B', type: 'text' },
      { id: 'qwen3-14b', name: 'Qwen3 14B', type: 'text' },
      { id: 'qwen3-8b', name: 'Qwen3 8B', type: 'text' },
      { id: 'qwen3-4b', name: 'Qwen3 4B', type: 'text' },
      // Reasoning
      { id: 'qwq-plus', name: 'QwQ Plus (推理)', type: 'text' },
      // Vision
      { id: 'qwen3-vl-max', name: 'Qwen3 VL Max (视觉)', type: 'text' },
      { id: 'qwen-vl-max', name: 'Qwen VL Max (视觉)', type: 'text' },
      { id: 'qwen-vl-plus', name: 'Qwen VL Plus (视觉)', type: 'text' },
      { id: 'qvq-max', name: 'QVQ Max (视觉推理)', type: 'text' },
      // Coder
      { id: 'qwen3-coder-plus', name: 'Qwen3 Coder Plus', type: 'text' },
      { id: 'qwen2.5-coder-32b-instruct', name: 'Qwen2.5 Coder 32B', type: 'text' },
      // Omni (multimodal text+audio+image+video)
      { id: 'qwen3.5-omni-plus', name: 'Qwen3.5 Omni Plus', type: 'text' },
      // Qwen2.5 text (still available)
      { id: 'qwen2.5-72b-instruct', name: 'Qwen2.5 72B', type: 'text' },
      { id: 'qwen2.5-32b-instruct', name: 'Qwen2.5 32B', type: 'text' },
      { id: 'qwen2.5-14b-instruct', name: 'Qwen2.5 14B', type: 'text' },
      { id: 'qwen2.5-7b-instruct', name: 'Qwen2.5 7B', type: 'text' },
      // Image / video
      { id: 'wanx2.1-t2i-turbo', name: 'Wanx 2.1 图片生成 Turbo', type: 'image' },
      { id: 'wanx2.1-t2i-plus', name: 'Wanx 2.1 图片生成 Plus', type: 'image' },
      { id: 'wanx2.1-t2v-plus', name: 'Wanx 2.1 视频生成', type: 'video' },
      // Audio
      { id: 'qwen-audio-turbo', name: 'Qwen Audio Turbo', type: 'audio' },
      // Embedding
      { id: 'text-embedding-v3', name: 'Text Embedding v3', type: 'text' },
      { id: 'text-embedding-v2', name: 'Text Embedding v2', type: 'text' },
    ],
  },

  baidu: {
    name: '百度文心 (ERNIE)',
    baseUrl: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat',
    authType: 'query-token',
    authHeader: '',
    billingType: 'both',
    apiFormat: 'baidu',
    loginUrl: 'https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application',
    docsUrl: 'https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html',
    subscriptionUrl: 'https://console.bce.baidu.com/billing/#/account/index',
    accessModes: ['apikey'],
    models: [
      // ERNIE 4.5
      { id: 'ernie-4.5-8k-preview', name: 'ERNIE 4.5 8K', type: 'text' },
      { id: 'ernie-4.5-turbo-8k-preview', name: 'ERNIE 4.5 Turbo 8K', type: 'text' },
      { id: 'ernie-4.5-turbo-128k-preview', name: 'ERNIE 4.5 Turbo 128K', type: 'text' },
      // ERNIE 4.0
      { id: 'completions_pro', name: 'ERNIE 4.0', type: 'text' },
      { id: 'ernie-4.0-turbo-8k', name: 'ERNIE 4.0 Turbo 8K', type: 'text' },
      { id: 'ernie-4.0-turbo-128k', name: 'ERNIE 4.0 Turbo 128K', type: 'text' },
      { id: 'ernie-4.0-8k-preview', name: 'ERNIE 4.0 8K Preview', type: 'text' },
      // ERNIE 3.5
      { id: 'completions', name: 'ERNIE 3.5 8K', type: 'text' },
      { id: 'ernie-3.5-128k', name: 'ERNIE 3.5 128K', type: 'text' },
      // ERNIE Speed / Lite / Tiny
      { id: 'ernie-speed-128k', name: 'ERNIE Speed 128K', type: 'text' },
      { id: 'ernie-speed-pro-128k', name: 'ERNIE Speed Pro 128K', type: 'text' },
      { id: 'ernie-lite-128k', name: 'ERNIE Lite 128K', type: 'text' },
      { id: 'ernie-lite-pro-128k', name: 'ERNIE Lite Pro 128K', type: 'text' },
      { id: 'ernie-tiny-8k', name: 'ERNIE Tiny 8K', type: 'text' },
    ],
  },

  minimax: {
    name: 'MiniMax (海螺AI)',
    baseUrl: 'https://api.minimax.chat/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    docsUrl: 'https://platform.minimaxi.com/document/Announcement',
    subscriptionUrl: 'https://platform.minimaxi.com/user-center/basic-information',
    accessModes: ['apikey', 'oauth'],
    oauth: {
      authorizeUrl: 'https://platform.minimaxi.com/oauth/authorize',
      tokenUrl: 'https://platform.minimaxi.com/oauth/token',
      scope: 'api',
    },
    models: [

      { id: 'MiniMax-M2.7', name: 'MiniMax M2.7', type: 'text' },
      { id: 'MiniMax-M2.7-highspeed', name: 'MiniMax M2.7 Highspeed', type: 'text' },
      { id: 'MiniMax-M2.5', name: 'MiniMax M2.5', type: 'text' },
      { id: 'MiniMax-M2.5-highspeed', name: 'MiniMax M2.5 Highspeed', type: 'text' },
      { id: 'MiniMax-M2.1', name: 'MiniMax M2.1', type: 'text' },
      { id: 'MiniMax-M2.1-highspeed', name: 'MiniMax M2.1 Highspeed', type: 'text' },
      { id: 'MiniMax-M2', name: 'MiniMax M2', type: 'text' },
      { id: 'speech-2.8-hd', name: 'Speech 2.8 HD', type: 'audio' },
      { id: 'speech-2.8-turbo', name: 'Speech 2.8 Turbo', type: 'audio' },
      { id: 'speech-2.6-hd', name: 'Speech 2.6 HD', type: 'audio' },
      { id: 'speech-2.6-turbo', name: 'Speech 2.6 Turbo', type: 'audio' },
      { id: 'speech-02-hd', name: 'Speech 02 HD', type: 'audio' },
      { id: 'speech-02-turbo', name: 'Speech 02 Turbo', type: 'audio' },
      { id: 'music-2.0', name: 'Music 2.0', type: 'audio' },
      { id: 'minimax-hailuo-2.3', name: 'MiniMax Hailuo 2.3', type: 'video' },
      { id: 'minimax-hailuo-2.3-fast', name: 'MiniMax Hailuo 2.3 Fast', type: 'video' },
      { id: 'minimax-hailuo-02', name: 'MiniMax Hailuo 02', type: 'video' },
      { id: 'image-01', name: 'Image 01', type: 'image' },
      { id: 'image-01-live', name: 'Image 01 Live', type: 'image' }
    ],
  },

  stepfun: {
    name: '阶跃星辰 (StepFun)',
    baseUrl: 'https://api.stepfun.com/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.stepfun.com/interface-key',
    docsUrl: 'https://platform.stepfun.com/docs/overview/concept',
    subscriptionUrl: 'https://platform.stepfun.com/account-management',
    accessModes: ['apikey'],
    models: [
      { id: 'step-2-16k', name: 'Step-2 16K', type: 'text' },
      { id: 'step-2-16k-exp', name: 'Step-2 16K Exp', type: 'text' },
      { id: 'step-1-200k', name: 'Step-1 200K', type: 'text' },
      { id: 'step-1-128k', name: 'Step-1 128K', type: 'text' },
      { id: 'step-1-32k', name: 'Step-1 32K', type: 'text' },
      { id: 'step-1v-32k', name: 'Step-1V 32K (视觉)', type: 'text' },
      { id: 'step-1.5v-mini', name: 'Step-1.5V Mini (视觉)', type: 'text' },
      { id: 'step-1x-medium', name: 'Step-1X Medium (图片)', type: 'image' },
    ],
  },

  doubao: {
    name: '豆包 (ByteDance)',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    docsUrl: 'https://www.volcengine.com/docs/82379',
    subscriptionUrl: 'https://console.volcengine.com/finance/unifiedBilling/detail',
    accessModes: ['apikey'],
    models: [
      { id: 'doubao-1.5-pro-32k', name: 'Doubao 1.5 Pro 32K', type: 'text' },
      { id: 'doubao-1.5-pro-256k', name: 'Doubao 1.5 Pro 256K', type: 'text' },
      { id: 'doubao-1.5-lite-32k', name: 'Doubao 1.5 Lite 32K', type: 'text' },
      { id: 'doubao-1.5-vision-pro-32k', name: 'Doubao 1.5 Vision Pro 32K', type: 'text' },
      { id: 'doubao-pro-32k', name: 'Doubao Pro 32K', type: 'text' },
      { id: 'doubao-pro-128k', name: 'Doubao Pro 128K', type: 'text' },
      { id: 'doubao-pro-256k', name: 'Doubao Pro 256K', type: 'text' },
      { id: 'doubao-lite-32k', name: 'Doubao Lite 32K', type: 'text' },
      { id: 'doubao-lite-128k', name: 'Doubao Lite 128K', type: 'text' },
      { id: 'seedream', name: 'Seedream 图片生成', type: 'image' },
      { id: 'doubao-embedding-large', name: 'Doubao Embedding Large', type: 'text' },
    ],
  },

  siliconflow: {
    name: 'SiliconFlow (硅基流动)',
    baseUrl: 'https://api.siliconflow.cn/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://cloud.siliconflow.cn/account/ak',
    docsUrl: 'https://docs.siliconflow.cn',
    subscriptionUrl: 'https://cloud.siliconflow.cn/account/charge',
    accessModes: ['apikey'],
    models: [
      // Aggregated models from multiple providers
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3', type: 'text' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1', type: 'text' },
      { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen2.5 72B', type: 'text' },
      { id: 'Qwen/Qwen2.5-32B-Instruct', name: 'Qwen2.5 32B', type: 'text' },
      { id: 'Qwen/Qwen2.5-7B-Instruct', name: 'Qwen2.5 7B', type: 'text' },
      { id: 'Qwen/Qwen2.5-Coder-32B-Instruct', name: 'Qwen2.5 Coder 32B', type: 'text' },
      { id: 'Qwen/QwQ-32B', name: 'QwQ 32B', type: 'text' },
      { id: 'Pro/Qwen/Qwen2.5-VL-7B-Instruct', name: 'Qwen2.5 VL 7B', type: 'text' },
      { id: 'THUDM/glm-4-9b-chat', name: 'GLM-4 9B', type: 'text' },
      { id: 'meta-llama/Llama-3.3-70B-Instruct', name: 'Llama 3.3 70B', type: 'text' },
      { id: 'google/gemma-2-27b-it', name: 'Gemma 2 27B', type: 'text' },
      // Image
      { id: 'stabilityai/stable-diffusion-3-5-large', name: 'SD 3.5 Large', type: 'image' },
      { id: 'black-forest-labs/FLUX.1-schnell', name: 'FLUX.1 Schnell', type: 'image' },
      { id: 'black-forest-labs/FLUX.1-dev', name: 'FLUX.1 Dev', type: 'image' },
    ],
  },

  mistral: {
    name: 'Mistral AI',
    baseUrl: 'https://api.mistral.ai/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.mistral.ai/api-keys',
    docsUrl: 'https://docs.mistral.ai',
    subscriptionUrl: 'https://console.mistral.ai/billing',
    accessModes: ['apikey'],
    models: [
      // Frontier Generalist
      { id: 'mistral-large-latest', name: 'Mistral Large 3', type: 'text' },
      { id: 'mistral-medium-latest', name: 'Mistral Medium 3.1', type: 'text' },
      { id: 'mistral-small-latest', name: 'Mistral Small 4', type: 'text' },
      // Reasoning
      { id: 'magistral-medium-latest', name: 'Magistral Medium', type: 'text' },
      { id: 'magistral-small-latest', name: 'Magistral Small', type: 'text' },
      // Code
      { id: 'codestral-latest', name: 'Codestral', type: 'text' },
      { id: 'devstral-latest', name: 'Devstral 2', type: 'text' },
      // Vision
      { id: 'pixtral-large-latest', name: 'Pixtral Large (视觉)', type: 'text' },
      // OCR
      { id: 'mistral-ocr-latest', name: 'Mistral OCR 3', type: 'text' },
      // Audio
      { id: 'mistral-voxtral-tts-latest', name: 'Voxtral TTS', type: 'audio' },
      { id: 'mistral-voxtral-mini-transcribe-latest', name: 'Voxtral Transcribe', type: 'audio' },
      // Embedding
      { id: 'mistral-embed', name: 'Mistral Embed', type: 'text' },
    ],
  },

  xai: {
    name: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://accounts.x.ai',
    docsUrl: 'https://docs.x.ai',
    subscriptionUrl: 'https://accounts.x.ai',
    accessModes: ['apikey'],
    models: [
      // Grok 4 (latest)
      { id: 'grok-4.20', name: 'Grok 4.20', type: 'text' },
      { id: 'grok-4', name: 'Grok 4 (Reasoning)', type: 'text' },
      // Grok 3
      { id: 'grok-3', name: 'Grok 3', type: 'text' },
      { id: 'grok-3-mini', name: 'Grok 3 Mini', type: 'text' },
      { id: 'grok-3-fast', name: 'Grok 3 Fast', type: 'text' },
      { id: 'grok-3-mini-fast', name: 'Grok 3 Mini Fast', type: 'text' },
      // Grok 2
      { id: 'grok-2-vision-1212', name: 'Grok 2 Vision', type: 'text' },
      { id: 'grok-2-1212', name: 'Grok 2', type: 'text' },
    ],
  },

  cohere: {
    name: 'Cohere',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://dashboard.cohere.com/api-keys',
    docsUrl: 'https://docs.cohere.com/docs/compatibility-api',
    subscriptionUrl: 'https://dashboard.cohere.com',
    accessModes: ['apikey'],
    models: [
      // Chat
      { id: 'command-a-03-2025', name: 'Command A', type: 'text' },
      { id: 'command-a-reasoning-08-2025', name: 'Command A Reasoning', type: 'text' },
      { id: 'command-a-vision-07-2025', name: 'Command A Vision', type: 'text' },
      { id: 'command-a-translate-08-2025', name: 'Command A Translate', type: 'text' },
      { id: 'command-r7b-12-2024', name: 'Command R7B', type: 'text' },
      // Embed
      { id: 'embed-v4.0', name: 'Embed v4.0', type: 'text' },
      { id: 'embed-multilingual-v3.0', name: 'Embed Multilingual v3.0', type: 'text' },
      // Rerank
      { id: 'rerank-v4.0-pro', name: 'Rerank v4.0 Pro', type: 'text' },
      { id: 'rerank-v4.0-fast', name: 'Rerank v4.0 Fast', type: 'text' },
      // Audio
      { id: 'cohere-transcribe-03-2026', name: 'Cohere Transcribe', type: 'audio' },
    ],
  },

  groq: {
    name: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.groq.com/keys',
    docsUrl: 'https://console.groq.com/docs/openai',
    subscriptionUrl: 'https://console.groq.com',
    accessModes: ['apikey'],
    models: [
      // Production
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile', type: 'text' },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant', type: 'text' },
      { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B', type: 'text' },
      { id: 'openai/gpt-oss-20b', name: 'GPT-OSS 20B', type: 'text' },
      // Preview
      { id: 'meta-llama/llama-4-scout-17b-16e-instruct', name: 'Llama 4 Scout', type: 'text' },
      { id: 'qwen/qwen3-32b', name: 'Qwen3 32B', type: 'text' },
      // Reasoning
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill 70B', type: 'text' },
      { id: 'qwen-qwq-32b', name: 'QwQ 32B', type: 'text' },
    ],
  },

  perplexity: {
    name: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://www.perplexity.ai/settings/api',
    docsUrl: 'https://docs.perplexity.ai',
    subscriptionUrl: 'https://www.perplexity.ai/settings/api',
    accessModes: ['apikey'],
    models: [
      { id: 'sonar', name: 'Sonar', type: 'text' },
      { id: 'sonar-pro', name: 'Sonar Pro', type: 'text' },
      { id: 'sonar-reasoning-pro', name: 'Sonar Reasoning Pro', type: 'text' },
      { id: 'sonar-deep-research', name: 'Sonar Deep Research', type: 'text' },
    ],
  },

  openrouter: {
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://openrouter.ai/settings/keys',
    docsUrl: 'https://openrouter.ai/docs/quickstart',
    subscriptionUrl: 'https://openrouter.ai/settings/credits',
    accessModes: ['apikey'],
    models: [
      { id: 'openai/gpt-5.4', name: 'OpenAI GPT-5.4', type: 'text' },
      { id: 'openai/gpt-4o', name: 'OpenAI GPT-4o', type: 'text' },
      { id: 'openai/gpt-4.1', name: 'OpenAI GPT-4.1', type: 'text' },
      { id: 'openai/o3', name: 'OpenAI o3', type: 'text' },
      { id: 'anthropic/claude-opus-4-6', name: 'Claude Opus 4.6', type: 'text' },
      { id: 'anthropic/claude-sonnet-4-6', name: 'Claude Sonnet 4.6', type: 'text' },
      { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet', type: 'text' },
      { id: 'google/gemini-2.5-pro', name: 'Gemini 2.5 Pro', type: 'text' },
      { id: 'google/gemini-2.5-flash', name: 'Gemini 2.5 Flash', type: 'text' },
      { id: 'deepseek/deepseek-chat', name: 'DeepSeek V3', type: 'text' },
      { id: 'deepseek/deepseek-r1', name: 'DeepSeek R1', type: 'text' },
      { id: 'x-ai/grok-4.20', name: 'Grok 4.20', type: 'text' },
      { id: 'x-ai/grok-3', name: 'Grok 3', type: 'text' },
      { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B', type: 'text' },
      { id: 'qwen/qwen-2.5-72b-instruct', name: 'Qwen2.5 72B', type: 'text' },
      { id: 'mistralai/mistral-large-latest', name: 'Mistral Large', type: 'text' },
    ],
  },

  together: {
    name: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://api.together.ai/settings/api-keys',
    docsUrl: 'https://docs.together.ai/docs/openai-api-compatibility',
    subscriptionUrl: 'https://api.together.ai/settings/billing',
    accessModes: ['apikey'],
    models: [
      { id: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8', name: 'Llama 4 Maverick', type: 'text' },
      { id: 'meta-llama/Llama-4-Scout-17B-16E-Instruct', name: 'Llama 4 Scout', type: 'text' },
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', name: 'Llama 3.3 70B Turbo', type: 'text' },
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3', type: 'text' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1', type: 'text' },
      { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', name: 'Qwen2.5 72B Turbo', type: 'text' },
      { id: 'Qwen/QwQ-32B', name: 'QwQ 32B', type: 'text' },
      { id: 'mistralai/Mixtral-8x22B-Instruct-v0.1', name: 'Mixtral 8x22B', type: 'text' },
      { id: 'black-forest-labs/FLUX.1-schnell-Free', name: 'FLUX.1 Schnell', type: 'image' },
      { id: 'black-forest-labs/FLUX.1.1-pro', name: 'FLUX 1.1 Pro', type: 'image' },
    ],
  },

  fireworks: {
    name: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://app.fireworks.ai/api-keys',
    docsUrl: 'https://docs.fireworks.ai/tools-sdks/openai-compatibility',
    subscriptionUrl: 'https://app.fireworks.ai',
    accessModes: ['apikey'],
    models: [
      { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', name: 'Llama 3.3 70B', type: 'text' },
      { id: 'accounts/fireworks/models/llama-v3p1-405b-instruct', name: 'Llama 3.1 405B', type: 'text' },
      { id: 'accounts/fireworks/models/deepseek-v3', name: 'DeepSeek V3', type: 'text' },
      { id: 'accounts/fireworks/models/deepseek-r1', name: 'DeepSeek R1', type: 'text' },
      { id: 'accounts/fireworks/models/qwen2p5-72b-instruct', name: 'Qwen2.5 72B', type: 'text' },
      { id: 'accounts/fireworks/models/mixtral-8x22b-instruct', name: 'Mixtral 8x22B', type: 'text' },
      { id: 'accounts/fireworks/models/firefunction-v2', name: 'FireFunction V2', type: 'text' },
    ],
  },

  tencent_hunyuan: {
    name: '腾讯混元 (HunYuan)',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://console.cloud.tencent.com/hunyuan/api-key',
    docsUrl: 'https://cloud.tencent.com/document/product/1729/111007',
    subscriptionUrl: 'https://console.cloud.tencent.com/expense',
    accessModes: ['apikey'],
    models: [
      { id: 'hunyuan-turbos-latest', name: 'HunYuan TurboS Latest', type: 'text' },
      { id: 'hunyuan-t1-latest', name: 'HunYuan T1 Latest', type: 'text' },
      { id: 'hunyuan-large', name: 'HunYuan Large', type: 'text' },
      { id: 'hunyuan-turbo', name: 'HunYuan Turbo', type: 'text' },
      { id: 'hunyuan-standard-256k', name: 'HunYuan Standard 256K', type: 'text' },
      { id: 'hunyuan-lite', name: 'HunYuan Lite', type: 'text' },
      { id: 'hunyuan-vision', name: 'HunYuan Vision', type: 'text' },
      { id: 'hunyuan-code', name: 'HunYuan Code', type: 'text' },
    ],
  },

  openai_codex: {
    name: 'OpenAI Codex (Coding Plan)',
    baseUrl: 'https://api.openai.com/v1',
    authType: 'oauth',
    authHeader: 'Authorization',
    billingType: 'subscription',
    apiFormat: 'openai',
    loginUrl: 'https://platform.openai.com/settings/organization/billing/overview',
    docsUrl: 'https://platform.openai.com/docs',
    subscriptionUrl: 'https://platform.openai.com/settings/organization/billing/overview',
    accessModes: ['oauth'],
    oauth: {
      authorizeUrl: 'https://auth.openai.com/authorize',
      tokenUrl: 'https://auth.openai.com/oauth/token',
      scope: 'openid profile',
    },
    models: [
      { id: 'gpt-5.4', name: 'GPT-5.4', type: 'text' },
      { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', type: 'text' },
      { id: 'gpt-5.4-nano', name: 'GPT-5.4 Nano', type: 'text' },
      { id: 'gpt-4.1', name: 'GPT-4.1', type: 'text' },
      { id: 'gpt-4.1-mini', name: 'GPT-4.1 Mini', type: 'text' },
      { id: 'gpt-4o', name: 'GPT-4o', type: 'text' },
      { id: 'o4-mini', name: 'o4 Mini', type: 'text' },
      { id: 'o3', name: 'o3', type: 'text' },
      { id: 'o3-mini', name: 'o3 Mini', type: 'text' },
    ],
  },

  github_copilot: {
    name: 'GitHub Copilot',
    baseUrl: 'https://api.githubcopilot.com/chat/completions',
    authType: 'token',
    authHeader: 'Authorization',
    billingType: 'subscription',
    apiFormat: 'openai',
    loginUrl: 'https://github.com/features/copilot',
    docsUrl: 'https://docs.github.com/en/copilot',
    subscriptionUrl: 'https://github.com/settings/copilot',
    accessModes: ['apikey', 'oauth'],
    oauth: {
      authorizeUrl: 'https://github.com/login/oauth/authorize',
      tokenUrl: 'https://github.com/login/oauth/access_token',
      scope: 'read:user',
    },
    models: [
      // GPT family
      { id: 'gpt-5.4', name: 'GPT-5.4', type: 'text' },
      { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', type: 'text' },
      { id: 'gpt-5.3-codex', name: 'GPT-5.3 Codex', type: 'text' },
      { id: 'gpt-5.2', name: 'GPT-5.2', type: 'text' },
      { id: 'gpt-5.2-codex', name: 'GPT-5.2 Codex', type: 'text' },
      { id: 'gpt-5.1', name: 'GPT-5.1', type: 'text' },
      { id: 'gpt-5.1-codex', name: 'GPT-5.1 Codex', type: 'text' },
      { id: 'gpt-5.1-codex-max', name: 'GPT-5.1 Codex Max', type: 'text' },
      { id: 'gpt-5.1-codex-mini', name: 'GPT-5.1 Codex Mini', type: 'text' },
      { id: 'gpt-5-mini', name: 'GPT-5 Mini', type: 'text' },
      { id: 'gpt-4.1', name: 'GPT-4.1', type: 'text' },
      { id: 'gpt-4o', name: 'GPT-4o', type: 'text' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini', type: 'text' },
      { id: 'o3-mini', name: 'o3 Mini', type: 'text' },
      { id: 'o4-mini', name: 'o4 Mini', type: 'text' },
      // Claude family
      { id: 'claude-opus-4.6', name: 'Claude Opus 4.6', type: 'text' },
      { id: 'claude-opus-4.5', name: 'Claude Opus 4.5', type: 'text' },
      { id: 'claude-sonnet-4.6', name: 'Claude Sonnet 4.6', type: 'text' },
      { id: 'claude-sonnet-4.5', name: 'Claude Sonnet 4.5', type: 'text' },
      { id: 'claude-sonnet-4', name: 'Claude Sonnet 4', type: 'text' },
      { id: 'claude-haiku-4.5', name: 'Claude Haiku 4.5', type: 'text' },
      // Gemini family
      { id: 'gemini-3.1-pro', name: 'Gemini 3.1 Pro', type: 'text' },
      { id: 'gemini-3-pro', name: 'Gemini 3 Pro', type: 'text' },
      { id: 'gemini-3-flash', name: 'Gemini 3 Flash', type: 'text' },
      { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', type: 'text' },
      // Others
      { id: 'grok-code-fast-1', name: 'Grok Code Fast 1', type: 'text' },
      { id: 'qwen-2.5', name: 'Qwen 2.5', type: 'text' },
    ],
  },

  kimi_coding: {
    name: 'Kimi Coding Plan',
    baseUrl: 'https://api.moonshot.cn/v1',
    authType: 'bearer',
    authHeader: 'Authorization',
    billingType: 'apikey',
    apiFormat: 'openai',
    loginUrl: 'https://platform.moonshot.cn/console/account',
    docsUrl: 'https://platform.moonshot.cn/docs',
    subscriptionUrl: 'https://platform.moonshot.cn/console/account',
    accessModes: ['apikey'],
    models: [
      { id: 'kimi-k2.7', name: 'Kimi K2.7 (Coding)', type: 'text' },
      { id: 'kimi-k2.5', name: 'Kimi K2.5 (Coding)', type: 'text' },
      { id: 'kimi-k2-thinking', name: 'Kimi K2 Thinking (Coding)', type: 'text' },
    ],
  },
};